#!/bin/bash
#This script is executed every time your instance is spawned.

github_deploy_key=$HOME/my_data/htb-bash-logs-id_rsa
bash_history_archive_location=$HOME/.logs
bash_history_backup_script=$HOME/bash-history-backup.sh

rm -rf ~/Public
rm -rf ~/Videos
rm -rf ~/Documents
rm -rf ~/Music
rm -rf ~/Templates
rm -rf ~/Pictures

[[ -d $HOME/.ssh ]] || mkdir $HOME/.ssh

#Setup ssh for github.com
cat > $HOME/.ssh/config << EOF
Host github.com
    IdentityFile $github_deploy_key
    StrictHostKeyChecking no

EOF

#Configure git
git config --global user.email "htb"
git config --global user.name "htb"

git clone git@github.com:jamalhabash/htb-bash-logs.git $bash_history_archive_location

#Create the bash history backup script file
cat > $bash_history_backup_script << EOF
#!/bin/bash
#Run this as a cron job */5 * * * *

cd $bash_history_archive_location
git add --all
git commit -m "save bash history"
git push

EOF

chmod +x $bash_history_backup_script

#Setup the cron job. This line will overwrite anything currently in the file.
echo "*/5 * * * * $bash_history_backup_script" | crontab -

#Append the generic bashrc to the existing file. Modifies how history is handled etc.
wget -q -O- https://raw.githubusercontent.com/jamalhabash/development-environment/main/bashrc >> $HOME/.bashrc
echo alias cdmd=\"cd $HOME/my_data\" >> $HOME/.bashrc
echo alias ghl='tempfunc(){ grep "$@" $bash_history_archive_location/*; unset -f tempfunc; }; tempfunc'
